"""Vendor the existing Google Fonts and Font Awesome assets without altering glyphs.
Run from any directory with Python 3; network access is needed only to refresh assets.
"""
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'src/assets'
CARLITO_URL = 'https://fonts.googleapis.com/css2?family=Carlito:ital,wght@0,400;0,700;1,400;1,700&display=swap'
FA_BASE = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/'
UA = 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'


def fetch(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA}), timeout=60) as response:
        return response.read()


def download(job):
    url, destination = job
    data = fetch(url)
    assert data[:4] == b'wOF2', url
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(data)


def main():
    carlito = fetch(CARLITO_URL).decode()
    jobs = []
    for url in dict.fromkeys(re.findall(r'url\((https://[^)]+)\)', carlito)):
        name = url.rsplit('/', 1)[1]
        assert name.endswith('.woff2')
        jobs.append((url, ASSETS / 'fonts/Carlito/web' / name))
        carlito = carlito.replace(url, '../fonts/Carlito/web/' + name)
    assert len(jobs) == 28, 'Review changed upstream font stylesheet before updating.'

    original = fetch(FA_BASE + 'css/all.min.css').decode()
    pages = [ROOT / 'index.html', *sorted((ROOT / 'src/pages').glob('*.html'))]
    classes = set()
    for page in pages:
        for value in re.findall(r'class="([^"]+)"', page.read_text()):
            classes.update(value.split())
    classes = {name for name in classes if name in ('fa', 'fas', 'fab') or name.startswith('fa-')}
    # Keep the original declarations and selector groups for the classes in use.
    rules = []
    clean = re.sub(r'/\*.*?\*/', '', original, flags=re.S)
    for selector, declarations in re.findall(r'([^{}]+)\{([^{}]*)\}', clean):
        used = any(re.search(r'\.' + re.escape(name) + r'(?![\w-])', selector) for name in classes)
        face = selector == '@font-face' and (
            'font-family:"Font Awesome 6 Brands"' in declarations or
            ('font-family:"Font Awesome 6 Free"' in declarations and 'font-weight:900;' in declarations)
        )
        if used or face:
            if face:
                declarations = re.sub(r',url\([^)]*\.ttf\) format\("truetype"\)', '', declarations)
                declarations = declarations.replace('../webfonts/', '../fonts/FontAwesome/')
            rules.append(selector + '{' + declarations + '}')
    for name in ('fa-brands-400.woff2', 'fa-solid-900.woff2'):
        jobs.append((FA_BASE + 'webfonts/' + name, ASSETS / 'fonts/FontAwesome' / name))
    with ThreadPoolExecutor(max_workers=8) as pool:
        list(pool.map(download, jobs))
    license_header = original[:original.index('*/') + 2]
    header = '/* Generated by scripts/vendor-fonts.py. Carlito: SIL OFL, ../fonts/Carlito/OFL.txt. */\n'
    korean = '''\n/* Loaded only when Korean text is present. */
@font-face { font-family: 'IBM Plex Sans KR'; font-style: normal; font-weight: 400; font-display: swap; src: url('../fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Regular.ttf') format('truetype'); }
@font-face { font-family: 'IBM Plex Sans KR'; font-style: normal; font-weight: 700; font-display: swap; src: url('../fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Bold.ttf') format('truetype'); }
'''
    (ASSETS / 'styles/fonts.css').write_text(header + carlito + korean)
    (ASSETS / 'styles/icons.css').write_text(license_header + '\n/* Generated for current HTML classes by scripts/vendor-fonts.py. */\n' + '\n'.join(rules) + '\n')
    print(f'Vendored {len(jobs)} unchanged WOFF2 files; icon CSS {len(original):,} -> {len((ASSETS / "styles/icons.css").read_bytes()):,} bytes.')


if __name__ == '__main__':
    main()
